### ISSUE TITLE
Don't count email sigs

### ISSUE THREAD

**Issue by jleyser** [samtregar/scoutbot#1]
cal is smart enough to stop tracking a thread when it gets to 'thanks for the help!' -- but thinks email signatures are meaningful content.

It'd be great if cal ignored everything past "--\n" when doing word counts.

**Comment by TheWalkers** [comment]
++.  best issue ever.

On Thu, Oct 1, 2015 at 4:53 PM, Jeff Leyser <notifications@github.com>
wrote:

> cal is smart enough to stop tracking a thread when it gets to 'thanks for
> the help!' -- but thinks email signatures are meaningful content.
>
> It'd be great if cal ignored everything past "--\n" when doing word counts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samtregar/scoutbot/issues/1>.
>



-- 
Patrick Michael Kane
We Also Walk Dogs
<pmk@wawd.com>

**Comment by samtregar** [comment]
Done - can't promise it's particularly smart but it'll try now!
