### ISSUE TITLE
Need a 'holiday' or 'closed' command

### ISSUE THREAD

**Issue by jleyser** [samtregar/scoutbot#3]
Cal spammed the hell out of Slack this morning, not knowing support was closed.

We need a way to tell cal to ignore everything for a fixed length of time, like 'holiday 2015-12-25'

**Comment by samtregar** [comment]
Done - the way to mark a holiday is to set the support shift to be covered by "Support Closed" or "Holiday".  I've done that for July 4th and Sept 5th already.
